services:
  heart-anomaly-api:
    build: .
    container_name: heart-anomaly-api
    restart: always
    ports:
      - "5004:5004"
    environment:
      DATASET_BASE_DIR: /data/Sonidos
      MODEL_DIR: /app/model_data
    volumes:
      - /home/Sonidos:/data/Sonidos:ro
      - ./model_data:/app/model_data
