services:
  heart-anomaly-api:
    build: .
    container_name: heart-anomaly-api
    ports:
      - "3004:3004"
    restart: always
    tmpfs:
      - /tmp
    volumes:
      - ./model_data:/app/model